# Copyright Cam Mannett 2020
#
# See LICENSE file
# 

# This workflow runs a barrage of tests in order to valid a PR
name: Pull Request Checker

on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Builds the unit tests and executes them
  unit_tests:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
      
    # Annoyingly I can't find a PPA with the latest lcov, so I have to download
    # the deb manually.  This shouldn't be necessary once the Ubuntu 20.04
    # runner comes out of preview
    - name: Update packages
      run: |
        wget http://mirrors.kernel.org/ubuntu/pool/universe/l/lcov/lcov_1.14-2_all.deb
        sudo add-apt-repository ppa:mhier/libboost-latest
        sudo apt install g++-10 libboost1.73-dev ./lcov_1.14-2_all.deb

    - name: Configure
      run: |
        mkdir ${GITHUB_WORKSPACE}/../build_unit_tests
        cd ${GITHUB_WORKSPACE}/../build_unit_tests
        cmake -DCMAKE_CXX_COMPILER=g++-10 -DCOVERAGE=ON ${GITHUB_WORKSPACE}
        make -j4 malbolge_test
        
    - name: Run unit tests
      run: |
        cd ${GITHUB_WORKSPACE}/../build_unit_tests/test
        ./malbolge_test -l test_suite

    - name: Calculate unit test coverage
      run: |
        cd ${GITHUB_WORKSPACE}/test
        ./calculate_test_coverage.sh ${GITHUB_WORKSPACE}/../build_unit_tests
